# Generated by Django 2.0.7 on 2018-07-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=140)),
                ('kind', models.PositiveIntegerField(choices=[(0, 'To Do'), (1, 'Doing'), (2, 'Done')])),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='kanban.Board')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('title', 'board')},
        ),
    ]
