# Generated by Django 2.0.6 on 2018-07-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('kind', models.PositiveIntegerField(choices=[(0, 'To Do'), (1, 'Doing'), (2, 'Done')])),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('status', models.CharField(max_length=140)),
            ],
        ),
    ]
